<a href="https://colab.research.google.com/github/Thammarach/Telco-Customer-Churn/blob/main/Telco_Customer_Churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [125]:
import pandas as pd

In [126]:
df = pd.read_csv('/content/drive/MyDrive/Dataset_KU/Telco-Customer-Churn - Telco-Customer-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,2889-FPWRM,Male,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),117.80,8684.80,Yes
1,7569-NMZYQ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,No
2,9739-JLPQJ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),117.50,8670.10,No
3,9788-HNGUT,Male,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),116.95,8594.40,No
4,8879-XUAHX,Male,0,Yes,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,116.25,8564.75,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
7039,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
7040,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
7041,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
7042,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [128]:
df.isnull().any()

customerID          False
gender              False
SeniorCitizen       False
Partner             False
Dependents          False
tenure              False
PhoneService        False
MultipleLines       False
InternetService     False
OnlineSecurity      False
OnlineBackup        False
DeviceProtection    False
TechSupport         False
StreamingTV         False
StreamingMovies     False
Contract            False
PaperlessBilling    False
PaymentMethod       False
MonthlyCharges      False
TotalCharges         True
Churn               False
dtype: bool

In [129]:
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [130]:
df.fillna(0, inplace=True)

In [131]:
df.set_index('customerID', inplace=True)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
2889-FPWRM,Male,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),117.80,8684.80,Yes
7569-NMZYQ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),118.75,8672.45,No
9739-JLPQJ,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),117.50,8670.10,No
9788-HNGUT,Male,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),116.95,8594.40,No
8879-XUAHX,Male,0,Yes,No,71,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,116.25,8564.75,No

In [132]:
cat_columns = df.select_dtypes('object').columns
cat_columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='object')

In [133]:
telcoData_cat = pd.get_dummies(df[cat_columns],drop_first=True)
telcoData_cat

,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
customerID,,,,,,,,,,,,,,,,,,,,,
2889-FPWRM,1,1,0,1,0,1,1,0,0,1,...,1,0,1,1,0,1,0,0,0,1
7569-NMZYQ,0,1,1,1,0,1,1,0,0,1,...,1,0,1,0,1,1,0,0,0,0
9739-JLPQJ,0,1,1,1,0,1,1,0,0,1,...,1,0,1,0,1,0,1,0,0,0
9788-HNGUT,1,1,0,1,0,1,1,0,0,1,...,1,0,1,0,1,1,1,0,0,0
8879-XUAHX,1,1,0,1,0,1,1,0,0,1,...,1,0,1,0,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213-VVOLG,1,1,1,1,0,1,0,1,1,0,...,0,1,0,0,1,0,0,0,1,0
2520-SGTTA,0,1,1,1,0,0,0,1,1,0,...,0,1,0,0,1,0,0,0,1,0
2923-ARZLG,1,1,1,1,0,0,0,1,1,0,...,0,1,0,1,0,1,0,0,1,0
4075-WKNIU,0,1,1,1,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2775-SEFEE,1,0,1,1,0,1,0,0,0,1,...,0,0,0,0,1,1,0,0,0,0

In [134]:
num_columns = list(set(df.columns) - set(cat_columns))
num_columns

['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']

In [135]:
telcoData_prep = pd.concat([df[num_columns],telcoData_cat],axis=1)

In [136]:
telcoData_prep

,tenure,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
customerID,,,,,,,,,,,,,,,,,,,,,
2889-FPWRM,72,0,117.80,8684.80,1,1,0,1,0,1,...,1,0,1,1,0,1,0,0,0,1
7569-NMZYQ,72,0,118.75,8672.45,0,1,1,1,0,1,...,1,0,1,0,1,1,0,0,0,0
9739-JLPQJ,72,0,117.50,8670.10,0,1,1,1,0,1,...,1,0,1,0,1,0,1,0,0,0
9788-HNGUT,72,0,116.95,8594.40,1,1,0,1,0,1,...,1,0,1,0,1,1,1,0,0,0
8879-XUAHX,71,0,116.25,8564.75,1,1,0,1,0,1,...,1,0,1,0,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213-VVOLG,0,0,25.35,0.00,1,1,1,1,0,1,...,0,1,0,0,1,0,0,0,1,0
2520-SGTTA,0,0,20.00,0.00,0,1,1,1,0,0,...,0,1,0,0,1,0,0,0,1,0
2923-ARZLG,0,0,19.70,0.00,1,1,1,1,0,0,...,0,1,0,1,0,1,0,0,1,0
4075-WKNIU,0,0,73.35,0.00,0,1,1,1,0,1,...,1,0,0,0,1,0,0,0,1,0
2775-SEFEE,0,0,61.90,0.00,1,0,1,1,0,1,...,0,0,0,0,1,1,0,0,0,0

# Train test split

In [137]:
from sklearn.model_selection import train_test_split
telcoData_train, telcoData_test  = train_test_split(telcoData_prep, test_size=0.3)

In [138]:
telcoData_train

,tenure,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
customerID,,,,,,,,,,,,,,,,,,,,,
7140-ADSMJ,8,0,20.45,162.30,1,0,0,1,0,0,...,0,1,0,0,0,1,1,0,0,0
1334-FJSVR,1,0,24.25,24.25,1,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,1
5380-WJKOV,34,0,106.35,3549.25,1,0,0,1,0,1,...,1,0,1,0,0,1,0,1,0,1
3030-YZADT,9,0,44.95,431.00,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,1
5793-YOLJN,55,0,21.00,1210.30,0,1,1,1,0,0,...,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8434-PNQZX,42,0,78.45,3373.40,0,0,0,1,0,1,...,1,0,1,0,1,1,1,0,0,0
8158-WPEZG,11,0,35.65,425.10,1,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
0475-RIJEP,43,0,77.85,3365.85,1,0,0,1,0,1,...,0,0,0,0,0,1,0,1,0,1
4576-CSAJH,22,0,55.15,1193.05,1,0,0,1,0,0,...,0,0,0,1,0,1,1,0,0,1
7821-DPRQE,68,0,107.70,7320.90,1,1,0,1,0,1,...,1,0,1,0,0,1,0,1,0,0

In [142]:
pd.crosstab(telcoData_train['Churn_Yes'],columns='Prob',normalize=True) # ตรวจอัตราส่วนดูว่ามี 0 หรือ 1 ใน train มีเท่าไหร่

col_0          Prob
Churn_Yes
0          0.735294
1          0.264706

# KNN

In [146]:
from sklearn.neighbors import KNeighborsClassifier

In [153]:
knn = KNeighborsClassifier(n_neighbors=10)

In [154]:
knn.fit(telcoData_train.drop(columns='Churn_Yes'), 
         telcoData_train['Churn_Yes'])

KNeighborsClassifier(n_neighbors=10)

In [156]:
knn.score(telcoData_train.drop(columns='Churn_Yes'), 
         telcoData_train['Churn_Yes'])

0.8117647058823529

In [159]:
knn_tune = KNeighborsClassifier(4)
knn_tune.fit(telcoData_train.drop(columns='Churn_Yes'), 
         telcoData_train['Churn_Yes'])
knn_tune.score(telcoData_train.drop(columns='Churn_Yes'), 
         telcoData_train['Churn_Yes'])

0.8316430020283976

# k-fold cross-validation

In [160]:
from sklearn.model_selection import cross_val_score

In [161]:
knn10_cv = KNeighborsClassifier(10)
knn5_cv = KNeighborsClassifier(5)

result_knn10 = cross_val_score(knn10_cv,
                               telcoData_train.drop(columns='Churn_Yes'), 
                               telcoData_train['Churn_Yes'], 
                               cv=5)



result_knn5 = cross_val_score(knn5_cv,
                              telcoData_train.drop(columns='Churn_Yes'), 
                              telcoData_train['Churn_Yes'], 
                              cv=5)

In [162]:
result_knn10.mean(), result_knn5.mean()

(0.7780933062880325, 0.7707910750507099)

In [163]:
from sklearn.preprocessing import StandardScaler

In [164]:
std_scaler = StandardScaler()

In [165]:
std_scaler.fit(telcoData_train.drop(columns='Churn_Yes'))

StandardScaler()

In [169]:
X = telcoData_train.drop(columns='Churn_Yes')

In [170]:
Y = telcoData_train['Churn_Yes']

In [171]:
std_scaler.mean_, std_scaler.scale_

(array([3.23371197e+01, 1.59229209e-01, 6.47536511e+01, 2.28472353e+03,
        5.00202840e-01, 4.81338742e-01, 3.01014199e-01, 9.01419878e-01,
        9.85801217e-02, 4.15212982e-01, 4.37119675e-01, 2.15212982e-01,
        2.15212982e-01, 2.86612576e-01, 2.15212982e-01, 3.46247465e-01,
        2.15212982e-01, 3.44421907e-01, 2.15212982e-01, 2.96551724e-01,
        2.15212982e-01, 3.86815416e-01, 2.15212982e-01, 3.91277890e-01,
        2.08519270e-01, 2.45436105e-01, 5.90669371e-01, 2.22109533e-01,
        3.25963489e-01, 2.32048682e-01]),
 array([2.47394689e+01, 3.65889694e-01, 3.00827677e+01, 2.28971581e+03,
        4.99999959e-01, 4.99651636e-01, 4.58698867e-01, 2.98097436e-01,
        2.98097436e-01, 4.92758725e-01, 4.96030306e-01, 4.10970016e-01,
        4.10970016e-01, 4.52178955e-01, 4.10970016e-01, 4.75773221e-01,
        4.10970016e-01, 4.75179394e-01, 4.10970016e-01, 4.56737122e-01,
        4.10970016e-01, 4.87020790e-01, 4.10970016e-01, 4.88036375e-01,
        4.06249903e-01, 4.30345470e-01, 4.91710347e-01, 4.15664394e-01,
        4.68733712e-01, 4.22139895e-01]))

In [172]:
pd.DataFrame(zip(std_scaler.mean_, std_scaler.scale_), index=X.columns, columns=['mean','std']).T

,tenure,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
mean,32.337120,0.159229,64.753651,2284.723529,0.500203,0.481339,0.301014,0.901420,0.098580,0.415213,...,0.215213,0.386815,0.215213,0.391278,0.208519,0.245436,0.590669,0.222110,0.325963,0.232049
std,24.739469,0.365890,30.082768,2289.715810,0.500000,0.499652,0.458699,0.298097,0.298097,0.492759,...,0.410970,0.487021,0.410970,0.488036,0.406250,0.430345,0.491710,0.415664,0.468734,0.422140

In [173]:
X_transformed = std_scaler.transform(X)
X_std_scaled = pd.DataFrame(X_transformed, columns=X.columns)
X_std_scaled

,tenure,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,-0.983737,-0.435184,-1.472725,-0.926938,0.999594,-0.963349,-0.656235,0.330698,-0.330698,-0.842629,...,1.909597,-0.794248,1.909597,-0.801739,-0.513278,-0.570323,0.832463,1.871439,-0.695413,-0.549696
1,-1.266685,-0.435184,-1.346407,-0.987229,0.999594,-0.963349,-0.656235,-3.023910,3.023910,-0.842629,...,-0.523671,-0.794248,-0.523671,-0.801739,-0.513278,-0.570323,0.832463,-0.534348,1.437995,-0.549696
2,0.067216,-0.435184,1.382730,0.552264,0.999594,-0.963349,-0.656235,0.330698,-0.330698,1.186761,...,-0.523671,1.259052,-0.523671,1.247288,-0.513278,-0.570323,0.832463,-0.534348,1.437995,-0.549696
3,-0.943315,-0.435184,-0.658305,-0.809587,0.999594,-0.963349,-0.656235,0.330698,-0.330698,-0.842629,...,-0.523671,-0.794248,-0.523671,-0.801739,-0.513278,-0.570323,-1.201255,-0.534348,-0.695413,1.819187
4,0.916062,-0.435184,-1.454442,-0.469239,-1.000406,1.038046,1.523845,0.330698,-0.330698,-0.842629,...,1.909597,-0.794248,1.909597,-0.801739,-0.513278,1.753391,-1.201255,-0.534348,-0.695413,1.819187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4925,0.390586,-0.435184,0.455289,0.475464,-1.000406,-0.963349,-0.656235,0.330698,-0.330698,1.186761,...,-0.523671,1.259052,-0.523671,1.247288,-0.513278,1.753391,0.832463,1.871439,-0.695413,-0.549696
4926,-0.862473,-0.435184,-0.967453,-0.812163,0.999594,-0.963349,-0.656235,-3.023910,3.023910,-0.842629,...,-0.523671,-0.794248,-0.523671,-0.801739,-0.513278,-0.570323,0.832463,-0.534348,1.437995,-0.549696
4927,0.431007,-0.435184,0.435344,0.472166,0.999594,-0.963349,-0.656235,0.330698,-0.330698,1.186761,...,-0.523671,-0.794248,-0.523671,-0.801739,-0.513278,-0.570323,0.832463,-0.534348,1.437995,-0.549696
4928,-0.417839,-0.435184,-0.319241,-0.476772,0.999594,-0.963349,-0.656235,0.330698,-0.330698,-0.842629,...,-0.523671,-0.794248,-0.523671,-0.801739,1.948261,-0.570323,0.832463,1.871439,-0.695413,-0.549696
4929,1.441538,-0.435184,1.427606,2.199477,0.999594,1.038046,-0.656235,0.330698,-0.330698,1.186761,...,-0.523671,1.259052,-0.523671,1.247288,-0.513278,-0.570323,0.832463,-0.534348,1.437995,-0.549696

In [174]:
X_std_scaled.mean()

tenure                                  -1.207058e-16
SeniorCitizen                            3.583791e-16
MonthlyCharges                          -1.668262e-16
TotalCharges                             7.512584e-17
gender_Male                             -7.638695e-17
Partner_Yes                              1.993897e-16
Dependents_Yes                          -4.588171e-16
PhoneService_Yes                         2.382363e-16
MultipleLines_No phone service          -2.247019e-16
MultipleLines_Yes                        3.017645e-16
InternetService_Fiber optic             -2.770378e-16
InternetService_No                      -2.946482e-16
OnlineSecurity_No internet service      -2.946482e-16
OnlineSecurity_Yes                      -9.717266e-16
OnlineBackup_No internet service        -2.946482e-16
OnlineBackup_Yes                         7.044174e-17
DeviceProtection_No internet service    -2.946482e-16
DeviceProtection_Yes                    -1.134409e-15
TechSupport_No internet service         -2.946482e-16
TechSupport_Yes                         -9.048430e-16
StreamingTV_No internet service         -2.946482e-16
StreamingTV_Yes                         -4.631859e-16
StreamingMovies_No internet service     -2.946482e-16
StreamingMovies_Yes                     -3.419847e-16
Contract_One year                       -4.972583e-16
Contract_Two year                        4.517459e-17
PaperlessBilling_Yes                    -4.981816e-16
PaymentMethod_Credit card (automatic)    3.189020e-16
PaymentMethod_Electronic check          -5.332674e-17
PaymentMethod_Mailed check              -1.390639e-15
dtype: float64

In [175]:
X_std_scaled.std(ddof=0)

tenure                                   1.0
SeniorCitizen                            1.0
MonthlyCharges                           1.0
TotalCharges                             1.0
gender_Male                              1.0
Partner_Yes                              1.0
Dependents_Yes                           1.0
PhoneService_Yes                         1.0
MultipleLines_No phone service           1.0
MultipleLines_Yes                        1.0
InternetService_Fiber optic              1.0
InternetService_No                       1.0
OnlineSecurity_No internet service       1.0
OnlineSecurity_Yes                       1.0
OnlineBackup_No internet service         1.0
OnlineBackup_Yes                         1.0
DeviceProtection_No internet service     1.0
DeviceProtection_Yes                     1.0
TechSupport_No internet service          1.0
TechSupport_Yes                          1.0
StreamingTV_No internet service          1.0
StreamingTV_Yes                          1.0
StreamingMovies_No internet service      1.0
StreamingMovies_Yes                      1.0
Contract_One year                        1.0
Contract_Two year                        1.0
PaperlessBilling_Yes                     1.0
PaymentMethod_Credit card (automatic)    1.0
PaymentMethod_Electronic check           1.0
PaymentMethod_Mailed check               1.0
dtype: float64

In [176]:
from sklearn.model_selection import GridSearchCV

In [178]:
knn_search = KNeighborsClassifier()

In [185]:
grid_search_std_scaled = GridSearchCV(knn_search
                           , param_grid={'n_neighbors': (4,5,6,7,8,9,10,11,12)}
                           , cv=5)
grid_search_std_scaled.fit(X_std_scaled, Y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': (4, 5, 6, 7, 8, 9, 10, 11, 12)})

In [186]:
grid_search_std_scaled.best_params_, grid_search_std_scaled.best_score_

({'n_neighbors': 12}, 0.7827586206896552)

In [192]:
from sklearn.metrics import classification_report

In [193]:
telcoData_test

,tenure,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
customerID,,,,,,,,,,,,,,,,,,,,,
8221-HVAYI,35,0,69.15,2490.15,1,1,1,1,0,1,...,0,0,0,0,1,1,1,0,0,0
4304-XUMGI,50,1,75.15,3822.45,1,1,1,1,0,1,...,0,0,1,0,1,1,0,0,0,0
9251-AWQGT,48,0,20.00,935.90,0,1,1,1,0,0,...,0,1,0,0,1,0,0,0,1,0
5986-WWXDV,39,0,19.35,779.20,1,0,1,1,0,0,...,0,1,0,1,0,0,0,0,0,0
6833-JMZYP,15,0,94.00,1505.45,0,0,0,1,0,0,...,1,0,1,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2509-TFPJU,72,0,25.75,1864.20,1,1,0,1,0,1,...,0,1,0,0,1,0,1,0,0,0
9481-SFCQY,14,0,59.80,824.85,0,0,1,1,0,0,...,1,0,0,0,0,1,1,0,0,0
4418-LZMSV,13,0,61.80,750.10,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9483-GCPWE,9,0,20.10,190.25,1,0,1,1,0,0,...,0,1,0,1,0,0,0,0,1,0
1731-TVIUK,4,0,93.50,362.20,0,0,0,1,0,1,...,0,0,1,0,0,1,0,1,0,1

In [194]:
knn_tune = KNeighborsClassifier(4)

In [195]:
knn_tune.fit(telcoData_train.drop(columns='Churn_Yes'), 
         telcoData_train['Churn_Yes'])

KNeighborsClassifier(n_neighbors=4)

In [196]:
res = knn_tune.predict(telcoData_test.drop(columns='Churn_Yes'))

In [197]:
print(classification_report(y_true=telcoData_test['Churn_Yes'].values, y_pred=res))

              precision    recall  f1-score   support

           0       0.79      0.93      0.85      1549
           1       0.62      0.31      0.41       564

    accuracy                           0.76      2113
   macro avg       0.70      0.62      0.63      2113
weighted avg       0.74      0.76      0.73      2113